name: Labeler and Reviewer Assignment
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - master

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  assign_reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/auto_assign.yml"