name: Python Package using Conda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          echo "CONDA_SUBDIR=classic" >> $GITHUB_ENV
          conda update -n base -c defaults conda
          echo $CONDA/bin >> $GITHUB_PATH
          conda env update --file environment.yml --name base

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r strategic_fruits_card_detection.egg-info/requires.txt

      - name: Build and Install Package
        run: |
          pip install --upgrade build pip
          python -m build
          pip install dist/*.whl

      - name: Lint and Test
        run: |
          conda install flake8 pytest
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          pytest