name: Python Package using Conda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          conda update -n base -c defaults conda
          echo $CONDA/bin >> $GITHUB_PATH
          conda env update --file environment.yml --name base

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.3'

      - name: Lint and Test
        run: |
          conda install flake8 pytest
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          pytest