name: Automated Semantic Versioning

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  versioning:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.12.3]
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version pytest

      - name: Generate release notes
        run: |
          gem install github_changelog_generator
          github_changelog_generator -u MacMat01 -p strategic-fruits-card-detection --token ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        id: bump_version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          bump2version patch setup.py --dry-run --allow-dirty --verbose | grep 'New version will be' | sed -r s,'^.* will be ','',g > version
          echo "BUMPED_VERSION=$(cat version)" >> $GITHUB_ENV
          bump2version patch setup.py --commit --tag

      - name: Push changes
        run: |
          git push origin master --tags